pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["add_jurnal.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Jurnal &#62; Jurnal Umum &#62; Add Jurnal","Add Jurnal",""],
["add_perkiraan.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Perkiraan &#62; Add Perkiraan","Add Perkiraan",""],
["admin_pengguna.php","Sistem Applikasi &#62; Admin Pengguna","Admin Pengguna",""],
["anggota.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Anggota","Anggota",""],
["backup_database.php","Backup Database","Backup Database",""],
["barang_kredit.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Penjualan &#62; Barang Kredit","Barang Kredit",""],
["barang_terjual.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Penjualan &#62; Barang Terjual","Barang Terjual",""],
["buku_besar.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Jurnal &#62; Buku Besar","Buku Besar",""],
["chapter_2.php","Sistem Applikasi","Sistem Applikasi",""],
["daftar_anggota.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Keanggotaan &#62; Daftar Anggota","Daftar Anggota",""],
["daftar_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang &#62; Daftar Barang","Daftar Barang",""],
["data_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang","Data Barang",""],
["departement.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Departement","Departement",""],
["grafik_penjualan.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Grafik Penjualan","Grafik Penjualan",""],
["grafik_shu.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Laporan &#62; Grafik SHU","Grafik SHU",""],
["instalasi_applikasi.php","Sistem Applikasi &#62; Instalasi Applikasi","Instalasi Applikasi",""],
["introduction.php","Pendahuluan","Pendahuluan",""],
["jenis_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang &#62; Jenis Barang","Jenis Barang",""],
["jurnal.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Jurnal","Jurnal",""],
["jurnal_umum.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Jurnal &#62; Jurnal Umum","Jurnal Umum",""],
["kategori_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang &#62; Kategori Barang","Kategori Barang",""],
["keanggotaan.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Keanggotaan","Keanggotaan",""],
["klasifikasi.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Klasifikasi","Klasifikasi",""],
["konversi_satuan.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang &#62; Konversi Satuan","Konversi Satuan",""],
["laporan.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Laporan","Laporan",""],
["laporan2.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan","Laporan",""],
["laporan_pembelian.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Pembelian","Laporan Pembelian",""],
["laporan_penjualan.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Penjualan","Laporan Penjualan",""],
["laporan_stock.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Stock","Laporan Stock",""],
["list_jurnal_umum.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Jurnal &#62; Jurnal Umum &#62; List Jurnal Umum","List Jurnal Umum",""],
["list_user.php","Sistem Applikasi &#62; Admin Pengguna &#62; List User","List User",""],
["modul-modul.php","Pendahuluan &#62; Modul-modul","Modul-modul",""],
["modul_inventory.php","Sistem Applikasi &#62; Modul Inventory","Modul Inventory",""],
["neraca.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Laporan &#62; Neraca","Neraca",""],
["neraca_lajur.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Laporan &#62; Neraca Lajur","Neraca Lajur",""],
["new_topic.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi","Kode Akuntansi",""],
["overview.php","Sistem Applikasi &#62; Kebutuhan Sistem","Kebutuhan Sistem",""],
["pemasok.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Pemasok","Pemasok",""],
["pembelian_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Pembelian Barang","Pembelian Barang",""],
["pengaturan_hak_akses.php","Sistem Applikasi &#62; Admin Pengguna &#62; Pengaturan Hak Akses","Pengaturan Hak Akses",""],
["penjualan_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Penjualan Barang","Penjualan Barang",""],
["penjualan_kredit2.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Penjualan &#62; Penjualan Kredit","Penjualan Kredit",""],
["penjualan_tunai2.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Penjualan &#62; Penjualan Tunai","Penjualan Tunai",""],
["perkiraan.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Perkiraan","Perkiraan",""],
["perkiraan2.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Perkiraan &#62; Daftar Perkiraan","Daftar Perkiraan",""],
["posting_penjualan_kredit.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Posting Inventory &#62; Posting Penjualan Kredit","Posting Penjualan Kredit",""],
["poting_inventory.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Posting Inventory","Posting Inventory",""],
["return_pembelian_konsinyasi.php","Sistem Applikasi &#62; Modul Inventory &#62; Pembelian Barang &#62; Return Pembelian Konsinyasi","Return Pembelian Konsinyasi",""],
["return_penjualan.php","Sistem Applikasi &#62; Modul Inventory &#62; Penjualan Barang &#62; Return Penjualan","Return Penjualan",""],
["ruang_lingkup.php","Pendahuluan &#62; Ruang Lingkup","Ruang Lingkup",""],
["setting_neraca.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Tools &#62; Setting Neraca","Setting Neraca",""],
["setting_shu.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Tools &#62; Setting SHU","Setting SHU",""],
["shu.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Laporan &#62; SHU","SHU",""],
["simpanan_anggota.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Keanggotaan &#62; Simpanan Anggota","Simpanan Anggota",""],
["stock_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Stock &#62; Stock Barang","Stock Barang",""],
["stock_history.php","Sistem Applikasi &#62; Modul Inventory &#62; Laporan &#62; Laporan Stock &#62; Stock History","Stock History",""],
["sub_chapter_2_1.php","Sistem Applikasi &#62; Modul Akuntansi","Modul Akuntansi",""],
["sub_klasifikasi.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Kode Akuntansi &#62; Sub Klasifikasi","Sub Klasifikasi",""],
["tambah_anggota.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Keanggotaan &#62; Tambah Anggota","Tambah Anggota",""],
["tambah_barang.php","Sistem Applikasi &#62; Modul Inventory &#62; Data Barang &#62; Tambah Barang","Tambah Barang",""],
["tambah_user.php","Sistem Applikasi &#62; Admin Pengguna &#62; Tambah User","Tambah User",""],
["tools.php","Sistem Applikasi &#62; Modul Akuntansi &#62; Tools","Tools",""],
["welcome_topic.php","Pendahuluan &#62; Pendahuluan","Pendahuluan",""]];
